# File: agents/self_refine.py
"""Let Gemini critique and improve its own insight using a feedback loop."""

from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnableLambda
from langchain_google_genai import ChatGoogleGenerativeAI

# Load Gemini Flash again
llm = ChatGoogleGenerativeAI(
    model="gemini-2.0-flash",
    temperature=0.4,
    max_output_tokens=2048,
)

CRITIQUE_PROMPT = ChatPromptTemplate.from_template("""
You're a senior marketing strategist. Here's an insight generated by a junior AI:

---
{draft}
---

Critique it constructively. What could be clearer, more actionable, or more data-grounded?
Return an improved version below:

Improved Insight:
""")

# One-shot self-improvement

def self_refine(draft: str) -> str:
    chain = CRITIQUE_PROMPT | llm
    refined = chain.invoke({"draft": draft})
    return refined.content.strip()

# Example usage:
# improved = self_refine("CTR dipped in March. Maybe update creatives.")
